name: Green CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  greenframeci:

    runs-on: ubuntu-latest

    env:
      Solution_Name: GreenCoding.sln   
                      
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore
      
    - name: Publish the Blazor app
      run: dotnet publish -c Release -o ./publish

    - name: Start the Blazor app
      run: |
        dotnet ./publish/Blazor.dll &
        echo "Waiting for Blazor app to start..."
      env:
        ASPNETCORE_URLS: "http://localhost:5000" # Ensure your app starts on this URL
          
    - name: Install Greenframe
      run: curl https://assets.greenframe.io/install.sh | bash

    - name: Analyze with Greenframe
      run: greenframe analyze http://localhost:5000
      env:
        GREENFRAME_SECRET_TOKEN: ${{ secrets.GREENFRAME_SECRET_TOKEN }} # Make sure to add your Greenframe API key in GitHub secrets

    - name: Upload Greenframe results
      uses: actions/upload-artifact@v2
      with:
        name: greenframe-results
        path: greenframe-results/

   # - name: Install Greenframe
   #   run: npm install -g @greenframe/cli

   # - name: Analyze with Greenframe
   #   run: greenframe analyze
   #   env:
   #      GREENFRAME_SECRET_TOKEN: ${{secrets.GREENFRAME_SECRET_TOKEN}}

   # - run: curl https://assets.greenframe.io/install.sh | bash

   # - run: greenframe analyze
   #   env:
   #     baseURL: http://localhost:8080
   #     GREENFRAME_SECRET_TOKEN: ${{secrets.GREENFRAME_SECRET_TOKEN}}
