name: Green CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  greenframeci:

    runs-on: ubuntu-latest

    env:
      Solution_Name: GreenCoding.sln   
                      
    services:
      selenium:
        image: selenium/standalone-chrome
        ports:
          - 4444:4444
        options: >-
          --health-cmd "curl -f http://localhost:4444/wd/hub/status || exit 1"
          --health-interval 5s
          --health-timeout 5s
          --health-retries 20
          
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore
      
    - name: Publish the Blazor app
      run: dotnet publish -c Release -o ./publish

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install Greenframe
      run: npm install -g @greenframe/cli

    - name: Analyze with Greenframe
      run: greenframe analyze
      env:
         GREENFRAME_SECRET_TOKEN: ${{secrets.GREENFRAME_SECRET_TOKEN}}

   # - run: curl https://assets.greenframe.io/install.sh | bash

   # - run: greenframe analyze
   #   env:
   #     baseURL: http://localhost:8080
   #     GREENFRAME_SECRET_TOKEN: ${{secrets.GREENFRAME_SECRET_TOKEN}}
