name: Green CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  greenframeci:

    runs-on: ubuntu-latest
    env:
      Solution_Name: GreenCoding.sln                         

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
      

   # - run: curl https://assets.greenframe.io/install.sh | bash

   # - run: greenframe analyze
   #   env:
   #     baseURL: http://localhost:8080
   #     GREENFRAME_SECRET_TOKEN: ${{secrets.GREENFRAME_SECRET_TOKEN}}
